project_id = "romulkwdhzrnlvagmcfj"

[functions.externalapi]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.analyze-book-cover]
verify_jwt = false

[functions.robot-ai]
verify_jwt = false
